version: '3.8'
services:
  web:
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
    command: >
      sh -c
      "
      yarn install
      && yarn dev -- --host 0.0.0.0 &
      tail -f /dev/null
      "
